name: CI

on:
  pull_request:
  merge_group:

jobs:
  check:
    name: Use this action for check
    strategy:
      matrix:
        runner: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    permissions:
      contents: read # for checkout
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Use kotlin-gradle action
        uses: ./kotlin-gradle/
      - name: Check that annotation is displayed
        run: |
          # kotlin-gradle
          echo 'w: file://${{ github.workspace }}/kotlin-gradle/action.yml:3:4 This is message for kotlin-gradle-compiler-warning'
          echo 'e: file://${{ github.workspace }}/kotlin-gradle/action.yml:7:8 This is message for kotlin-gradle-compiler-error'
          echo 'w: ${{ github.workspace }}/kotlin-gradle/action.yml: (1, 2): This is message for kotlin-gradle-old-compiler-warning'
          echo 'e: ${{ github.workspace }}/kotlin-gradle/action.yml: (5, 6): This is message for kotlin-gradle-old-compiler-error'
      - name: Check out samlpe project 
        uses: actions/checkout@v4
        with:
          repository: google/iosched
          path: sample
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
      - name: Build samlpe project for checking annotation
        run: cd sample && ./gradlew assembleDebug
